name: Django CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.11']

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}

              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pipenv'

            - name: Install pipenv
              run: pip install pipenv

            - name: Install dependencies
              run: pipenv sync --dev

            - name: Build static
              run: |
                  sudo apt-get update
                  wget -qO- https://deb.nodesource.com/setup_18.x | sudo bash -
                  sudo apt-get install -y nodejs
                  npm install -g pnpm
                  pnpm install
                  pnpm build

            - name: Setup staticfiles
              run: pipenv run python manage.py collectstatic --noinput

            - name: Lint
              run: pipenv run ruff .

            - name: Test
              run: pipenv run pytest --cov
